Resources:
  CustomersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.customersTableName}
      AttributeDefinitions:
        - AttributeName: _id
          AttributeType: S
      KeySchema:
        - AttributeName: _id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST